[project]
name = "langgraph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "deepagents>=0.7.4",
    "edgartools>=5.56.0",
    "fastembed>=0.8.1",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-openai>=1.4.3",
    "langchain-openviking>=0.1.0",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.10",
    "loguru>=0.7.3",
    "markdownify>=1.2.3",
    "nm-memory-layer",
    "openai>=2.53.0",
    "prompt-toolkit>=3.0.53",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "sqlite-vec>=0.1.9",
    "statistics>=1.0.3.5",
    "tavily>=1.1.0",
]

[tool.uv.sources]
nm-memory-layer = { git = "https://github.com/trgordonb/nm-memory-layer", branch = "main" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
